Parent method intercept
ray-di/Ray.Aop pull request #181
Opened 2021-12-03 17:54 UTC by NaokiTsuchiya

2021-12-03 17:55 UTC, NaokiTsuchiya commented on src/CodeGenMethod.php
> +/** @SuppressWarnings(PHPMD.CouplingBetweenObjects) */
これはあと1つ依存を減らせばpassできますが、例外をassertに置き換えるくらいしかできなさそうなのでsuppressしました

2021-12-04 16:22 UTC, koriym requested changes

2021-12-04 16:22 UTC, koriym commented on src/CodeGenMethod.php
> +    private function getClassName(CodeVisitor $code): string
```suggestion
   /**
    * @return class-string
    */
    private function getClassName(CodeVisitor $code): string
```

2021-12-04 16:23 UTC, koriym commented on src/CodeGenMethod.php
> +    private function getClassName(CodeVisitor $code): string
新規で追加した分で`class-string`使えるところは使ってはどうでしょうか。

2021-12-05 05:56 UTC, NaokiTsuchiya commented on src/CodeGenMethod.php
> +    private function getClassName(CodeVisitor $code): string
suggestion 取り入れて、SAもsootheしました 👍

2021-12-05 08:31 UTC, koriym requested changes

2021-12-05 08:31 UTC, koriym commented on tests/Fake/FakeMockChild.php
> +
```suggestion
```

2021-12-05 08:31 UTC, koriym commented on tests/Fake/FakeMockChildChild.php
> +
```suggestion
```

2021-12-05 23:14 UTC, koriym commented
https://github.com/nikic/PHP-Parser/blob/master/doc/component/FAQ.markdown#how-can-the-parent-of-a-node-be-obtained

これを見落としてました、

2021-12-06 12:41 UTC, koriym approved these changes

2021-12-06 12:41 UTC, merged

2022-02-03 02:46 UTC, SerjoA commented
thank you for your hard and excellent work

2022-02-03 02:48 UTC, koriym commented
@SerjoA Thank you for using Ray.Aop! cc/ @NaokiTsuchiya